[지연] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/29-westagram-backend-2-team pull request #13
Opened 2022-01-18 02:41 UTC by jiyeon-kim-ds

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 시 비밀번호 암호화 적용
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 사용자가 회원가입 시 작성한 비밀번호가 암호화 되어 데이터베이스에 저장됨

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-18 06:04 UTC, lordmyshepherd requested changes

2022-01-18 06:04 UTC, lordmyshepherd commented on students/jiyeon/users/views.py
> +class LoginView(View):
이미 앞 PR에서 merge된 코드입니다. 새로운 PR이 merge 되었으니 main branch 최신화 후에 jiyeon/bcrypt_signup 브랜치도 최신화해서 올려주세요!

정리하자면, 해당 PR에는 암호화 적용 관련된 코드만 올라올 수 있도록 수정해주세요~

```python

```

2022-01-18 06:40 UTC, jiyeon-kim-ds commented on students/jiyeon/users/views.py
> +class LoginView(View):
pull 하고 수정된 사항만 올라오도록 수정했습니다. 감사합니다!

2022-01-20 01:05 UTC, lordmyshepherd requested changes

2022-01-20 01:05 UTC, lordmyshepherd commented on students/jiyeon/users/views.py
> +                password      = hashed_password,
값을 decode해서 저장할 수 있도록 수정해주세요~

2022-01-20 01:09 UTC, lordmyshepherd commented on students/jiyeon/users/views.py
> +                password      = hashed_password,
Mission 6에 포함되어 있는 내용인 것 같습니다. Mission 5 PR은 닫아주세요~

2022-01-20 01:29 UTC, closed without merging