[혜린] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/29-westagram-backend-2-team pull request #16
Opened 2022-01-18 06:07 UTC by OolongTea620

## 수정 사항 간략한 한줄 요약
- 로그인 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일과  비밀번호로 로그인을 할 수 있다
- 빈 값이 있는 경우 400  에러 반환
- 로그인 시도 실패시 401 에러 반환
- 로그인 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-18 06:13 UTC, lordmyshepherd requested changes

2022-01-18 06:13 UTC, lordmyshepherd commented on students/hyelin/westargram/users/views.py
> +from django.http import JsonResponse
불필요한 import문은 지워주시고, import문 순서를 잘 지켜서 만들어주세요.
위와 같은 순서대로 import 하는 모듈을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요.

(python convention 문서 참고해주세요.)

```python
# 파이썬 built-in 모듈
import json
import re

# 외부 모듈
from django.http      import JsonResponse
from django.views     import View

# 내가 만든 사용자 모듈
from users.models     import User
```

추가로 주석은 전부 지워주세요!  (주석 없이 이해할 수 있는 코드가 좋은 코드입니다~!)

2022-01-18 06:13 UTC, lordmyshepherd commented on students/hyelin/westargram/users/views.py
> +class SignUpView (View):
앞에 PR에 이미 존재하는 코드 이므로 해당 PR에서는 지워주세요~

2022-01-18 06:13 UTC, lordmyshepherd commented on students/hyelin/westargram/users/views.py
> +            return JsonResponse( {"message": "KEY_ERROR"}, status=400)
가독성을 위해서 Key Error는 Try, except로 처리해주세요!

2022-01-18 06:13 UTC, lordmyshepherd commented on students/hyelin/westargram/users/views.py
> +            print(login_info)
프린트문은 지워주세요~

2022-01-18 06:13 UTC, lordmyshepherd commented on students/hyelin/westargram/users/views.py
> +            login_info = User.objects.get(email__exact=data['email'])
`User.objects.get(email__exact=data['email'])` 코드가 실행되면 반환하는 값은 로그인 정보가 아니라 사용자(user) 정보에요!
변수명을 정할 때 변수가 참조하고 있는 객체가 어떤 값을 담고 있는지 알 수 있도록 만들어주세요~

```suggestion
            user = User.objects.get(email__exact=data['email'])
```

2022-01-18 06:36 UTC, OolongTea620 commented on students/hyelin/westargram/users/views.py
> +            login_info = User.objects.get(email__exact=data['email'])
- [x]

2022-01-18 06:39 UTC, OolongTea620 commented on students/hyelin/westargram/users/views.py
> +            login_info = User.objects.get(email__exact=data['email'])
✅

2022-01-18 06:39 UTC, OolongTea620 commented on students/hyelin/westargram/users/views.py
> +            print(login_info)
✅

2022-01-18 06:40 UTC, OolongTea620 commented on students/hyelin/westargram/users/views.py
> +class SignUpView (View):
✅

2022-01-18 06:40 UTC, OolongTea620 commented on students/hyelin/westargram/users/views.py
> +from django.http import JsonResponse
✅

2022-01-18 07:55 UTC, OolongTea620 commented on students/hyelin/westargram/users/views.py
> +            return JsonResponse( {"message": "KEY_ERROR"}, status=400)
체크!

2022-01-19 07:21 UTC, lordmyshepherd reviewed
LGTM 👍🏻

2022-01-19 07:21 UTC, merged