Mission 2. [지현] modeling
wecode-bootcamp-korea/29-westagram-backend-2-team pull request #6
Opened 2022-01-13 08:00 UTC by JHYUNNY

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 모델링 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- git init 하는 문제 수정
- main에서 branch 만든 후 -> 수정 -> git add . git commit -m, git push origin 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-13 08:10 UTC, lordmyshepherd requested changes

2022-01-13 08:10 UTC, lordmyshepherd commented on students/jihyun/westagram/users/models.py
> +        db_table = 'phonenumbers'
이름, 이메일, 비밀번호를 전부 테이블로 분리한 이유가 있으신가요?
사용자 정보를 모두 포함하고 있는 사용자(User) 테이블로 합쳐주세요~ 

```suggestion

class User(models.Model) :
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    password = models.CharField(max_length=20)
    email = models.ForeignKey(Email, on_delete=models.CASCADE)
    phonenumber = models.CharField(max_length=20)
            
    class Meta :
        db_table = 'users'
```

2022-01-14 02:11 UTC, bigfanoftim requested changes

2022-01-14 02:11 UTC, bigfanoftim commented on students/jihyun/westagram/users/models.py
> +    phonenumber = models.CharField(max_length=20)
가독성을 위해 `=` 혹은 `:`를 기준으로 정렬해주세요!

```python
name     = models.CharField(max_length=30)
email    = models.CharField(max_length=50)
password = models.CharField(max_length=50)
```

2022-01-14 02:11 UTC, bigfanoftim commented on students/jihyun/westagram/users/models.py
> +    password = models.CharField(max_length=20)
password property는 나중에 해시(암호화)된 비밀번호 길이를 고려해서 넉넉하게 200 이상으로 설정해주세요.

2022-01-14 02:11 UTC, bigfanoftim commented on students/jihyun/westagram/users/models.py
> +    email = models.ForeignKey(Email, on_delete=models.CASCADE)
`email`을 참조하는 이유가 있을까요? 모델링 수정된 것을 반영해주세요!

2022-01-14 02:11 UTC, bigfanoftim commented on students/jihyun/westagram/users/models.py
> +    email = models.ForeignKey(Email, on_delete=models.CASCADE)
추가로 `email field`에 `unique` 속성을 추가하셔서 유저가 중복 저장되는 문제가 발생하지 않도록 수정해주세요!
공식 문서에서 그 방법을 찾아보고 적용해주세요.

2022-01-14 06:15 UTC, bigfanoftim requested changes

2022-01-14 06:15 UTC, bigfanoftim commented on students/jihyun/westagram/users/views.py
> +                return JsonResponse({'message' : 'FAILED'}, status=400)
지현님! 해당 PR은 modeling 관련 PR입니다. 앞으로 GitHub PR을 작성하시는 경우 항상 하나의 PR(브랜치)에는 하나의 기능만 올라오도록 수정해주세요!
```suggestion
```

2022-01-14 06:15 UTC, bigfanoftim commented on students/jihyun/westagram/users/urls.py
> +    path('/userview',UserView.as_view()),
마찬가지로 모델링과 관련없는 코드는 다 지워주세요.
```suggestion
```

2022-01-14 06:15 UTC, bigfanoftim commented on students/jihyun/westagram/users/models.py
> +    address     = models.EmailField(Unique=True)
`email`을 저장해야하니 컬럼명도 `email`이라고 해주면 좋겠습니다. 또한 `max_length` 옵션도 추가해주시면 좋을 것 같아요~

2022-01-14 07:13 UTC, lordmyshepherd requested changes

2022-01-14 07:13 UTC, lordmyshepherd commented on students/jihyun/user/models.py
> +    phonenumber = models.CharField(max_length=20)
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2022-01-14 07:13 UTC, lordmyshepherd commented on students/jihyun/user/models.py
> +    address     = models.EmailField(Unique=True)
address 보다는 email이 더 명확하게 의미가 전달될 것 같습니다!
address -> email로 수정 부탁드려요~

2022-01-18 05:50 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-01-18 05:50 UTC, merged