[지연] Misson 3 회원가입 View 기능 정의
wecode-bootcamp-korea/29-westagram-backend-2-team pull request #7
Opened 2022-01-14 04:14 UTC by jiyeon-kim-ds

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입을 위한 views.py 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 입력된 이름,이메일,비밀번호,휴대폰 번호를 중복 확인(이메일)하고 데이터베이스에 정보를 전달하는 views.py 추가
- URLconf의 내용을 수정하여 회원가입 View를 호출할 수 있도록 함

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 위코드 코딩 컨벤션에 관한 질문이 있습니다.
```
def anyfunc():
...

return any_value
```
위와 같이 def문이나 for문에서 값을 return할 때 주로 중간에 한 줄 띄어서 쓰나요? 
위스터디 코딩 컨벤션 페이지에서는 사례를 찾기 어려워서 질문드립니다!
## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-01-14 06:30 UTC, lordmyshepherd commented on students/jiyeon/users/views.py
> +        regex_password = re.compile(r'^(?=.*\w)(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$')
정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.
추가로 아래에서 `'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'`는 상수이기 때문에 대문자로 변수명을 정해주셔야 합니다-!

```python
import re

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

if not re.match(REGEX_EMAIL, value):
    ..
if not re.match(REGEX_EMAIL, value):
    ..
```

2022-01-14 06:34 UTC, lordmyshepherd commented on students/jiyeon/users/views.py
> +            pass
에러가 발생했는데 pass 하시는 이유가 있을까요?

2022-01-14 06:35 UTC, lordmyshepherd commented on students/jiyeon/users/views.py
> +                )
`data['email']`에서 key error가 raise되는 경우 처리를 어떻게 해야될까요?

```suggestion
        if re.fullmatch(regex_email, data['email']) == None: # 이메일 양식에 맞게 입력 되었는지 확인
            
            return JsonResponse({"E-mail Error": "양식에 맞는 메일 주소를 입력해주세요."})
        
        if re.fullmatch(regex_password, data['password']) == None: # 비밀번호 조건에 맞게 입력되었는지 확인
            
            return JsonResponse(
                {"Password Error": "8자리 이상의 알파벳, 숫자, 특수문자(@$!%*?&)를 포함한 비밀번호를 입력해주세요."}
                )
```

2022-01-14 06:36 UTC, lordmyshepherd commented on students/jiyeon/users/views.py
> +        if re.fullmatch(regex_password, data['password']) == None: # 비밀번호 조건에 맞게 입력되었는지 확인
fullmatch() 호출 후에 반환되는 None값은 falsy한 값이기 때문에 `==None`을 할 필요가 없습니다.

```suggestion
        if re.fullmatch(regex_password, data['password']): # 비밀번호 조건에 맞게 입력되었는지 확인
```

2022-01-14 07:03 UTC, jiyeon-kim-ds commented on students/jiyeon/users/views.py
> +            pass
1. email이 중복된 경우에는 try문은 filtered_query에 쿼리셋을 저장하고
2. email이 중복되지 않는 경우에는 `User.objects.get()` 코드를 실행할 때 `User.DoesNotExist`가 발생해 except문이 실행되기 때문에 pass를 사용했습니다. 코드 가독성 측면에서 if문으로 바꿔 좀 더 이해하기 쉽게 하는 것이 좋을 것 같네요! 감사합니다!

2022-01-14 07:36 UTC, jiyeon-kim-ds commented on students/jiyeon/users/views.py
> +                )
여기서 말씀하시는 Key Error는 POST 요청시 존재하지 않는 Key를 입력한 경우일까요?

2022-01-14 08:44 UTC, jiyeon-kim-ds commented
@lordmyshepherd 병민님 Key Error Raise에 관한 사항을 제외하고 모두 수정하였습니다. 확인 부탁드립니다. 피드백 감사합니다!

2022-01-17 01:49 UTC, lordmyshepherd requested changes

2022-01-17 01:49 UTC, lordmyshepherd commented on students/jiyeon/users/views.py
> +            return JsonResponse({"E-mail Error": f"중복된 이메일로 가입을 시도했습니다."}, status=400)
Error가 다른데 동일한 에러 메세지를 반환하고 있네요.
raise된 error에 맞는 메세지를 리턴해주세요.

2022-01-17 01:49 UTC, lordmyshepherd commented on students/jiyeon/users/views.py
> +            )
`get_or_create()`를 아주 잘 사용해 주셨습니다.~!
관련해서 2가지 피드백을 드릴 수 있을 것 같습니다.
1. get_or_create()를 계속 사용한다면, 사용법을 다시 한번 찾아봐야될 것 같습니다. default 속성을 사용하지 않는다면, 이름 한글자만 달라져도 새로운 유저로 생성이 되어 버립니다.
![스크린샷 2022-01-17 오전 10 46 30](https://user-images.githubusercontent.com/53214510/149688387-27d66d17-a97b-4993-a867-4ba042a157ba.png)

2. `get_or_create()` method의 경우에는 create 혹은 get 이후에 가져온 user정보를 가지고 이후에 추가로 사용하는 경우에 더욱 적합한 함수입니다. `exists()` method를 사용해서 가볍게 True/False만을 확인한 후에 사용자를 생성하는 로직이 가독성 측면에서 더 좋습니다.

```python
예)
 if not User.objects.filter().exists():
    Objects.create..
    return ..
```

2022-01-17 02:44 UTC, jiyeon-kim-ds commented
@lordmyshepherd 병민님 말씀 해주신대로 get_or_create 메서드 대신 .exists()로 변경하였습니다. get_or_create()에 대해 좀 더 공부해봐야 할 것 같네요. 감사합니다!

2022-01-17 04:53 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-01-17 04:55 UTC, lordmyshepherd requested changes

2022-01-17 04:55 UTC, lordmyshepherd commented on students/jiyeon/users/views.py
> +            return JsonResponse({"E-mail Error": "양식에 맞는 메일 주소를 입력해주세요."}, status=400)
`data["email"]` 코드에서 data 안에 email이 없는 경우에는 어떤 에러가 발생할 수 있을까요?

```suggestion
        if not re.fullmatch(REGEX_EMAIL, data['email']): # 이메일 양식에 맞게 입력 되었는지 확인
            return JsonResponse({"E-mail Error": "양식에 맞는 메일 주소를 입력해주세요."}, status=400)
```

2022-01-17 04:55 UTC, lordmyshepherd commented on students/jiyeon/users/views.py
> +            return JsonResponse({"E-mail Error": "이미 가입된 회원입니다."}, status=401)
else는 없어도 될 것 같습니다~
```suggestion
        return JsonResponse({"E-mail Error": "이미 가입된 회원입니다."}, status=401)
```

2022-01-17 06:49 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-01-17 06:49 UTC, merged